// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a4f5ae309857434140d3859b5f53e69eb690a6c2/vimeo/index.d.ts
interface VimeoParams {
	name:string;
	value:any;
}

interface VimeoPlayerAPI {
    (method: string): any;
    (method: string, callback: (value: any, player_id: any) => void): any;
	(method: string, value: any): any;
	(method: string, value: VimeoParams[]): any;
}

interface VimeoPlayer {
    api: VimeoPlayerAPI;
    addEvent(eventName: string, callback: (e: any) => void): any;
    removeEvent(eventName: string): void;
    postMessage(method: string, params:VimeoParams[], target: any): void;
    onMessageReceived(event: any): any;
    storeCallback(eventName: string, callback: any, target_id: string): any;
    getCallback(eventName: string, target_id: string): any;
    removeCallback(eventName: string, target_id: string): any;
    getDomainFromUrl(url: string): string;
}

declare var $f: VimeoPlayerAPI;declare var Froogaloop: VimeoPlayerAPI;
